version: "3"
services:
  emulator:
    image: gcr.io/flow-container-registry/emulator:0.20.2
    ports:
      - "8080:8080"
      - "3569:3569"
    environment:
      - FLOW_SERVICEPRIVATEKEY=84f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
